-------------------------
-- Slovak Localization String resources
-- miuios.cz (2014)
-- ingbzry
-------------------------
localization_Slovak_table = {
    calories_table={
        {str="≈1 duo z varených vajec",	calories=96},
        {str="≈1 krajec chleba",	calories=100},
        {str="≈1 ľadový čaj",	calories=112},
        {str="≈1 omeleta",	calories=118},
        {str="≈2 mäsá na špajdli",	calories=124},
        {str="≈1 plechovka Coca-Cola",	calories=153},
        {str="≈3 mäsá na špajdli",	calories=186},
        {str="≈2 duo z varených vajec",	calories=192},
        {str="≈2 krajce chleba",	calories=200},
        {str="≈1 miska ryže",	calories=210},
        {str="≈1 chlieb",	calories=221},
        {str="≈1 balíček cukríkov",	calories=223},
        {str="≈2 plechovky ľadového čaju",	calories=224},
        {str="≈1 malé hranolky",	calories=224},
        {str="≈1 tartelette",	calories=224},
        {str="≈2 omeletys",	calories=236},
        {str="≈4 mäsá na špajdli",	calories=248},
        {str="≈1 hamburger",	calories=260},
        {str="≈1 beignet",	calories=270},
        {str="≈1 petit pain de viande",	calories=272},
        {str="≈3 duo z varených vajec",	calories=288},
        {str="≈1 cône",	calories=290},
        {str="≈3 krajce chleba",	calories=300},
        {str="≈2 canettes de Coca-Cola",	calories=306},
        {str="≈1 moyenne frite",	calories=328},
        {str="≈3 omeletys",	calories=354},
        {str="≈1 tartelette aux œufs",	calories=375},
        {str="≈4 krajce chleba",	calories=400},
        {str="≈1 grande frite",	calories=402},
        {str="≈2 bols de riz",	calories=420},
        {str="≈2 pains",	calories=442},
        {str="≈2 paquet de dragibus",	calories=446},
        {str="≈2 tartelettes",	calories=448},
        {str="≈1 paquet de nouilles instantanées",	calories=470},
        {str="≈5 krajce chleba",	calories=500},
        {str="≈1 assiette de riz frit",	calories=516},
        {str="≈2 hamburgers",	calories=520},
        {str="≈2 beignets",	calories=540},
        {str="≈2 petits pains de viande",	calories=544},
        {str="≈2 cônes",	calories=580},
        {str="≈1 bol de nouilles instantanées",	calories=581},
        {str="≈1 bol de nouilles au boeuf",	calories=593},
        {str="≈10 mäsá na špajdli",	calories=620},
        {str="≈3 bols de riz",	calories=630},
        {str="≈3 pains",	calories=663},
        {str="≈2 tartelettes aux œufs",	calories=750},
        {str="≈3 beignets",	calories=810},
        {str="≈3 petits pains de viande",	calories=816},
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='mesiac',
    day='deň',
    step="krok",
    km='km',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d h',

    welcome_use="Vitajte, ja som váš MiBand",
    last_week_walked_format='Minulý týždeň ste prešli %d krokov',
    last_week_walked_info_format='Prešli ste %d km a spálili %d cal',
    last_month_walked_format='Minulý mesiac ste prešli %d krokov',
    last_month_walked_info_format='Prešli ste %d km a spálili %d cal',

    get_over_format=", okolo %d gramov tuku",
    click_to_get_help="Pozrite sa čo dokáže MiBand",
    take_a_walk="Prejdite sa s MiBand",
    take_a_walk_info="MiBand bude zaznamenávať vašu aktivitu a pomôže vám byť zdravý.",
    unlock_hint="Odomknite váš telefón s MiBand,",
    unlock_hint_info="objavte nový spôsob ochrany vášho súkromia.",
    no_data_hint_0="Hýbte sa a športujte pre vaše zdravie.",
    no_data_hint_1="Chcete byť stále šťastný? Zabehajte si.",
    no_data_hint_2="Kardio cvičenie vás osvieži a rozhýbe každý deň! ",
    no_data_hint_3="Bežný dospelý človek strávi 15%-20% spánku v hlbokej fáze. ",
    not_binded_hint="Nemáte prepojený MiBand s týmto účtom, prepojte ho teraz. ",
    new_record_info="WoW! Práve ste zdolali rekord v chôdzi.",
    new_record_format="Nový rekord, %d krokov, %s %d",
    today_goal_reached="Gratulujeme! Dosiahli ste váš dnešný cieľ. ",
    week_continue_reach_goal="Splnili ste váš denný cieľ po celý týždeň! To bol skvelý týždeň!",
    challenge_format="Dosiahli ste váš cieľ pre %d dní!",
    personal_best_format="Váš najväčší rekord je %d dní!",
    active_time_format_0="%dh",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Zabehli ste %s. Skvelé!",
    activie_run_format_1="Zabehli ste %s. Len tak ďalej!",
    activie_run_format_2="Zabehli ste %s, Neskutočné!",
    activie_run_consumed="Spálili ste %d cal. %s",

    get_distance_format=", celkovo %dm",
    activity_walk_format="%s Chôdza %d krokov %s",
    activity_walk_consumed_format="Spálené %d cal %s",

    activity_activity_format="%s %s v pohybe %s",
    last_night_sleeped_good_format="Minulú noc, ste spali %dh %dmin. Skvelý spánok!",
    last_night_sleeped_normal_format="Minulú noc, ste spali %dh %dmin",
    deep_sleep_format="Hlboká fáza spánku bola %dh %dmin",

    battery_low_info="Batéria je vybitá, pripojte MiBand na nabíjačku.",
    battery_very_low_info="Pripojte na nabíjačku",

    cannot_find_bracelet="Nebolo možné nájsť váš MiBand?",
    cannot_find_bracelet_info="Uistite sa, že váš MiBand je nabitý a nachádza sa v blízkosti vášho telefónu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Dosiahli ste svoj rekord!",
    new_record_born="Nový rekord!",
 }
