-------------------------
-- English Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_English_table = {
    calories_table={

    },

    ok='OK',

    hour='hrs',
    minute='min',
    month='month',
    day='day',
    step="step",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%d hrs %d min',
    hour_format='%d hrs',

    welcome_use="Hello, I am your Mi Band.",
    last_week_walked_format='Last week, you walked %d steps.',
    last_week_walked_info_format='Walked %d km, burned %d cal.',
    last_month_walked_format='Last month, you walked %d steps.',
    last_month_walked_info_format='Walked %d km, burned %d cal.',

    get_over_format=", about %d gram of fat.",
    click_to_get_help="Find out more to do with Mi Band.",
    take_a_walk="Take a walk with Mi Band.",
    take_a_walk_info="Mi Band will track your activities and help you to be healthier.",
    unlock_hint="Unlock phone with your Mi Band",
    unlock_hint_info="say Goodbye to the old times.",
    no_data_hint_0="Keep moving, make sports a part of your life.",
    no_data_hint_1="Want to stay happy? Just run.",
    no_data_hint_2="Cardio workout will make you light and fresh every day! ",
    no_data_hint_3="A normal adult spends 15%-20% of total sleep time in deep sleep stage. ",
    not_binded_hint="You haven’t linked any Mi Band to this account, please link one now. ",
    new_record_info="WoW! You just broke a record in walking.",
    new_record_format="New record, %d steps, %s %d",
    today_goal_reached="Congrats! You have achieved your goal today. ",
    week_continue_reach_goal="You have achieved your goal every day for an entire week! What an awesome week!",
    challenge_format="You have achieved your goal for %d days!",
    personal_best_format="Your highest record is %d days!",
    active_time_format_0="%d min",
    active_time_format_1="%d hr",
    active_time_format_2="%d hr %d min",
    activie_run_format_0="Ran %s. Good job!",
    activie_run_format_1="Ran %s. You are doing fantastic!",
    activie_run_format_2="Ran %s, Incredible endurance!",
    activie_run_consumed="Burned %d cal. %s",

    get_distance_format=", a total of %d m.",
    activity_walk_format="%s Walked %d steps %s",
    activity_walk_consumed_format="Burned %d cal %s",

    activity_activity_format="%s %s work out %s",
    last_night_sleeped_good_format="Last night, you slept for %s. What a great sleep!",
    last_night_sleeped_normal_format="Last night, you slept for %s.",
    deep_sleep_format="Deep sleep stage was %s.",

    battery_low_info="Low in battery, please charge your Mi Band.",
    battery_very_low_info="Connect to power",

    cannot_find_bracelet="Unable to find your Mi Band?",
    cannot_find_bracelet_info="Please make sure your Mi Band has power and stays nearby your phone.",

    challenge_to_get="%s days from making a new record!",
    record_reach_max="You have hit your highest record!",
    new_record_born="New record!",
 }

 localization_Slovak_table = {
    calories_table={
        {str=" ",	calories=96},
        {str=" ",	calories=100},
        {str=" ",	calories=112},
        {str=" ",	calories=118},
        {str=" ",	calories=124},
        {str=" ",	calories=153},
        {str=" ",	calories=186},
        {str=" ",	calories=192},
        {str=" ",	calories=200},
        {str=" ",	calories=210},
        {str=" ",	calories=221},
        {str=" ",	calories=223},
        {str=" ",	calories=224},
        {str=" ",	calories=224},
        {str=" ",	calories=224},
        {str=" ",	calories=236},
        {str=" ",	calories=248},
        {str=" ",	calories=260},
        {str=" ",	calories=270},
        {str=" ",	calories=272},
        {str=" ",	calories=288},
        {str=" ",	calories=290},
        {str=" ",	calories=300},
        {str=" ",	calories=306},
        {str=" ",	calories=328},
        {str=" ",	calories=354},
        {str=" ",	calories=375},
        {str=" ",	calories=400},
        {str=" ",	calories=402},
        {str=" ",	calories=420},
        {str=" ",	calories=442},
        {str=" ",	calories=446},
        {str=" ",	calories=448},
        {str=" ",	calories=470},
        {str=" ",	calories=500},
        {str=" ",	calories=516},
        {str=" ",	calories=520},
        {str=" ",	calories=540},
        {str=" ",	calories=544},
        {str=" ",	calories=580},
        {str=" ",	calories=581},
        {str=" ",	calories=593},
        {str=" ",	calories=620},
        {str=" ",	calories=630},
        {str=" ",	calories=663},
        {str=" ",	calories=750},
        {str=" ",	calories=810},
        {str=" ",	calories=816},
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='mesiac',
    day='deň',
    step="krok",
    km='km',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d h',

    welcome_use="Vitajte, ja som váš MiBand",
    last_week_walked_format='Minulý týždeň ste prešli %d krokov',
    last_week_walked_info_format='Prešli ste %d km a spálili %d cal',
    last_month_walked_format='Minulý mesiac ste prešli %d krokov',
    last_month_walked_info_format='Prešli ste %d km a spálili %d cal',

    get_over_format=", okolo %d gramov tuku",
    click_to_get_help="Pozrite sa čo dokáže MiBand",
    take_a_walk="Prejdite sa s MiBand",
    take_a_walk_info="MiBand bude zaznamenávať vašu aktivitu a pomôže vám byť zdravý.",
    unlock_hint="Odomknite váš telefón s MiBand,",
    unlock_hint_info="objavte nový spôsob ochrany vášho súkromia.",
    no_data_hint_0="Hýbte sa a športujte pre vaše zdravie.",
    no_data_hint_1="Chcete byť stále šťastný? Zabehajte si.",
    no_data_hint_2="Kardio cvičenie vás osvieži a rozhýbe každý deň! ",
    no_data_hint_3="Bežný dospelý človek strávi 15%-20% spánku v hlbokej fáze. ",
    not_binded_hint="Nemáte prepojený MiBand s týmto účtom, prepojte ho teraz. ",
    new_record_info="WoW! Práve ste zdolali rekord v chôdzi.",
    new_record_format="Nový rekord, %d krokov, %s %d",
    today_goal_reached="Gratulujeme! Dosiahli ste váš dnešný cieľ. ",
    week_continue_reach_goal="Splnili ste váš denný cieľ po celý týždeň! To bol skvelý týždeň!",
    challenge_format="Dosiahli ste váš cieľ pre %d dní!",
    personal_best_format="Váš najväčší rekord je %d dní!",
    active_time_format_0="%dmin",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Zabehli ste %s. Skvelé!",
    activie_run_format_1="Zabehli ste %s. Len tak ďalej!",
    activie_run_format_2="Zabehli ste %s, Neskutočné!",
    activie_run_consumed="Spálili ste %d cal. %s",

    get_distance_format=", celkovo %dm",
    activity_walk_format="%s Chôdza %d krokov %s",
    activity_walk_consumed_format="Spálené %d cal %s",

    activity_activity_format="%s %s v pohybe %s",
    last_night_sleeped_good_format="Minulú noc, ste spali %s. Skvelý spánok!",
    last_night_sleeped_normal_format="Minulú noc, ste spali %s",
    deep_sleep_format="Hlboká fáza spánku bola %s",

    battery_low_info="Batéria je vybitá, pripojte MiBand na nabíjačku.",
    battery_very_low_info="Pripojte na nabíjačku",

    cannot_find_bracelet="Nebolo možné nájsť váš MiBand?",
    cannot_find_bracelet_info="Uistite sa, že váš MiBand je nabitý a nachádza sa v blízkosti vášho telefónu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Dosiahli ste svoj rekord!",
    new_record_born="Nový rekord!",
 }
