-------------------------
-- Slovak Localization String resources
-- miui.cz (2014)
-- ingbzry
-------------------------
localization_Slovak_table = {
    calories_table={
        {str="≈1个茶叶蛋",	calories=96},
        {str="≈1片面包",	calories=100},
        {str="≈1瓶冰红茶",	calories=112},
        {str="≈1个煎蛋",	calories=118},
        {str="≈2串羊肉串",	calories=124},
        {str="≈1罐可乐",	calories=153},
        {str="≈3串羊肉串",	calories=186},
        {str="≈2个茶叶蛋",	calories=192},
        {str="≈2片面包",	calories=200},
        {str="≈1碗米饭",	calories=210},
        {str="≈1个馒头",	calories=221},
        {str="≈1根冰糖葫芦",	calories=223},
        {str="≈2瓶冰红茶",	calories=224},
        {str="≈1包小薯条",	calories=224},
        {str="≈1个蛋黄派",	calories=224},
        {str="≈2个煎蛋",	calories=236},
        {str="≈4串羊肉串",	calories=248},
        {str="≈1个汉堡",	calories=260},
        {str="≈1根油条",	calories=270},
        {str="≈1个肉包子",	calories=272},
        {str="≈3个茶叶蛋",	calories=288},
        {str="≈1个甜筒",	calories=290},
        {str="≈3片面包",	calories=300},
        {str="≈2罐可乐",	calories=306},
        {str="≈1包中薯条",	calories=328},
        {str="≈3个煎蛋",	calories=354},
        {str="≈1个蛋挞",	calories=375},
        {str="≈4片面包",	calories=400},
        {str="≈1包大薯条",	calories=402},
        {str="≈2碗米饭",	calories=420},
        {str="≈2个馒头",	calories=442},
        {str="≈2根冰糖葫芦",	calories=446},
        {str="≈1个蛋黄派",	calories=448},
        {str="≈1包方便面",	calories=470},
        {str="≈5片面包",	calories=500},
        {str="≈1盘蛋炒饭",	calories=516},
        {str="≈2个汉堡",	calories=520},
        {str="≈2根油条",	calories=540},
        {str="≈2个肉包子",	calories=544},
        {str="≈2个甜筒",	calories=580},
        {str="≈1碗方便面",	calories=581},
        {str="≈1碗牛肉拉面",	calories=593},
        {str="≈10串羊肉串",	calories=620},
        {str="≈3碗米饭",	calories=630},
        {str="≈3个馒头",	calories=663},
        {str="≈2个蛋挞",	calories=750},
        {str="≈3根油条",	calories=810},
        {str="≈3个肉包子",	calories=816},
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='mesiac',
    day='deň',
    step="krok",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d h',

    welcome_use="Vitajte, ja som váš MiBand",
    last_week_walked_format='Minulý týždeň ste prešli %d krokov',
    last_week_walked_info_format='Prešli ste %d km a spálili %d cal',
    last_month_walked_format='Minulý mesiac ste prešli %d krokov',
    last_month_walked_info_format='Prešli ste %d km a spálili %d cal',

    get_over_format=", okolo %d gramov tuku",
    click_to_get_help="Pozrite sa čo dokáže MiBand",
    take_a_walk="Prejdite sa s MiBand",
    take_a_walk_info="MiBand bude zaznamenávať vašu aktivitu a pomôže vám byť zdravý.",
    unlock_hint="Odomknite váš telefón s MiBand,",
    unlock_hint_info="objavte nový spôsob ochrany vášho súkromia.",
    no_data_hint_0="Hýbte sa a športujte pre vaše zdravie.",
    no_data_hint_1="Chcete byť stále šťastný? Zabehajte si.",
    no_data_hint_2="Kardio cvičenie vás osvieži a rozhýbe každý deň! ",
    no_data_hint_3="Bežný dospelý človek strávi 15%-20% spánku v hlbokej fáze. ",
    not_binded_hint="Nemáte prepojený MiBand s týmto účtom, prepojte ho teraz. ",
    new_record_info="WoW! Práve ste zdolali rekord v chôdzi.",
    new_record_format="Nový rekord, %d krokov, %s %d",
    today_goal_reached="Gratulujeme! Dosiahli ste váš dnešný cieľ. ",
    week_continue_reach_goal="Splnili ste váš denný cieľ po celý týždeň! To bol skvelý týždeň!",
    challenge_format="Dosiahli ste váš cieľ pre %d dní!",
    personal_best_format="Váš najväčší rekord je %d dní!",
    active_time_format_0="%dh",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Zabehli ste %s. Skvelé!",
    activie_run_format_1="Zabehli ste %s. Len tak ďalej!",
    activie_run_format_2="Zabehli ste %s, Neskutočné!",
    activie_run_consumed="Spálili ste %d cal. %s",

    get_distance_format=", celkovo %dm",
    activity_walk_format="%s Chôdza %d krokov %s",
    activity_walk_consumed_format="Spálené %d cal %s",

    activity_activity_format="%s %s v pohybe %s",
    last_night_sleeped_good_format="Minulú noc, ste spali %dh %dmin. Skvelý spánok!",
    last_night_sleeped_normal_format="Minulú noc, ste spali %dh %dmin",
    deep_sleep_format="Hlboká fáza spánku bola %dh %dmin",

    battery_low_info="Batéria je vybitá, pripojte MiBand na nabíjačku.",
    battery_very_low_info="Pripojte na nabíjačku",

    cannot_find_bracelet="Nebolo možné nájsť váš MiBand?",
    cannot_find_bracelet_info="Uistite sa, že váš MiBand je nabitý a nachádza sa v blízkosti vášho telefónu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Dosiahli ste svoj rekord!",
    new_record_born="Nový rekord!",
 }
