-------------------------
-- English Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_English_table = {
    calories_table={

    },

    ok='OK',

    hour='hrs',
    minute='min',
    month='month',
    day='day',
    step="step",
    km='km',
    minute_format='%d min',
    hour_minute_format='%d hrs %d min',
    hour_format='%d hrs',

    welcome_use="Hello, I am your Mi Band.",
    last_week_walked_format='Last week, you walked %d steps.',
    last_week_walked_info_format='Walked %d km, burned %d cal.',
    last_month_walked_format='Last month, you walked %d steps.',
    last_month_walked_info_format='Walked %d km, burned %d cal.',

    get_over_format=", about %d gram of fat.",
    click_to_get_help="Find out more to do with Mi Band.",
    take_a_walk="Take a walk with Mi Band.",
    take_a_walk_info="Mi Band will track your activities and help you to be healthier.",
    unlock_hint="Unlock phone with your Mi Band",
    unlock_hint_info="say Goodbye to the old times.",
    no_data_hint_0="Keep moving, make sports a part of your life.",
    no_data_hint_1="Want to stay happy? Just run.",
    no_data_hint_2="Cardio workout will make you light and fresh every day! ",
    no_data_hint_3="A normal adult spends 15%-20% of total sleep time in deep sleep stage. ",
    not_binded_hint="You haven’t linked any Mi Band to this account, please link one now. ",
    new_record_info="WoW! You just broke a record in walking.",
    new_record_format="New record, %d steps, %s %d",
    today_goal_reached="Congrats! You have achieved your goal today. ",
    week_continue_reach_goal="You have achieved your goal every day for an entire week! What an awesome week!",
    challenge_format="You have achieved your goal for %d days!",
    personal_best_format="Your highest record is %d days!",
    active_time_format_0="%d hr",
    active_time_format_1="%d hr",
    active_time_format_2="%d hr %d min",
    activie_run_format_0="Ran %s. Good job!",
    activie_run_format_1="Ran %s. You are doing fantastic!",
    activie_run_format_2="Ran %s, Incredible endurance!",
    activie_run_consumed="Burned %d cal. %s",

    get_distance_format=", a total of %d m.",
    activity_walk_format="%s Walked %d steps %s",
    activity_walk_consumed_format="Burned %d cal %s",

    activity_activity_format="%s %s work out%s",
    last_night_sleeped_good_format="Last night, you slept for %d hr %d min. What a great sleep!",
    last_night_sleeped_normal_format="Last night, you slept for %d hr %d min.",
    deep_sleep_format="Deep sleep stage was %d hr %d min.",

    battery_low_info="Low in battery, please charge your Mi Band.",
    battery_very_low_info="Connect to power",

    cannot_find_bracelet="Unable to find your Mi Band?",
    cannot_find_bracelet_info="Please make sure your Mi Band has power and stays nearby your phone.",

    challenge_to_get="%s days from making a new record!",
    record_reach_max="You have hit your highest record!",
    new_record_born="New record!",
 }
 
 -------------------------
-- Slovak Localization String resources
-- miuios.cz (2014)
-- ingbrzy
-------------------------
 
 localization_Slovak_table = {
    calories_table={
        {str="≈1 duo z vařenách vajec",	calories=96},
        {str="≈1 krajíc chleba",	calories=100},
        {str="≈1 ledový čaj",	calories=112},
        {str="≈1 omeleta",	calories=118},
        {str="≈2 masa na špejli",	calories=124},
        {str="≈1 plechovka Coca-Cola",	calories=153},
        {str="≈3 masa na špejli",	calories=186},
        {str="≈2 duo z vařených vajec",	calories=192},
        {str="≈2 krajíce chleba",	calories=200},
        {str="≈1 miska rýže",	calories=210},
        {str="≈1 chleba",	calories=221},
        {str="≈1 balíček cukroví",	calories=223},
        {str="≈2 plechovky ledového čaje",	calories=224},
        {str="≈1 malé hranolky",	calories=224},
        {str="≈1 tartelette",	calories=224},
        {str="≈2 omelety",	calories=236},
        {str="≈4 masa na špejli",	calories=248},
        {str="≈1 hamburger",	calories=260},
        {str="≈1 koblih",	calories=270},
        {str="≈1 sekaná",	calories=272},
        {str="≈3 duo z vařených vajec",	calories=288},
        {str="≈1 kornout",	calories=290},
        {str="≈3 krajíce chleba",	calories=300},
        {str="≈2 plechovky Coca-Cola",	calories=306},
        {str="≈1 střední hranolky",	calories=328},
        {str="≈3 omelety",	calories=354},
        {str="≈1 tartelette s vajíčkem",	calories=375},
        {str="≈4 krajíce chleba",	calories=400},
        {str="≈1 velké hranolky",	calories=402},
        {str="≈2 bols de riz",	calories=420},
        {str="≈2 bagety",	calories=442},
        {str="≈2 balíčky Dragibus",	calories=446},
        {str="≈2 tartelette",	calories=448},
        {str="≈1 instantní nudle",	calories=470},
        {str="≈5 krajíců chleba",	calories=500},
        {str="≈1 smažené rizoto",	calories=516},
        {str="≈2 hamburgery",	calories=520},
        {str="≈2 buchty",	calories=540},
        {str="≈2 petits pains de viande",	calories=544},
        {str="≈2 kornoutky",	calories=580},
        {str="≈1 bol de nouilles instantanées",	calories=581},
        {str="≈1 bol de nouilles au boeuf",	calories=593},
        {str="≈10 mas na šmejli",	calories=620},
        {str="≈3 bols de riz",	calories=630},
        {str="≈3 pains",	calories=663},
        {str="≈2 tartelettes aux œufs",	calories=750},
        {str="≈3 koblihy",	calories=810},
        {str="≈3 petits pains de viande",	calories=816},
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='mesiac',
    day='deň',
    step="krok",
    km='km',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d h',

    welcome_use="Vitajte, ja som váš MiBand",
    last_week_walked_format='Minulý týždeň ste prešli %d krokov',
    last_week_walked_info_format='Prešli ste %d km a spálili %d cal',
    last_month_walked_format='Minulý mesiac ste prešli %d krokov',
    last_month_walked_info_format='Prešli ste %d km a spálili %d cal',

    get_over_format=", okolo %d gramov tuku",
    click_to_get_help="Pozrite sa čo dokáže MiBand",
    take_a_walk="Prejdite sa s MiBand",
    take_a_walk_info="MiBand bude zaznamenávať vašu aktivitu a pomôže vám byť zdravý.",
    unlock_hint="Odomknite váš telefón s MiBand,",
    unlock_hint_info="objavte nový spôsob ochrany vášho súkromia.",
    no_data_hint_0="Hýbte sa a športujte pre vaše zdravie.",
    no_data_hint_1="Chcete byť stále šťastný? Zabehajte si.",
    no_data_hint_2="Kardio cvičenie vás osvieži a rozhýbe každý deň! ",
    no_data_hint_3="Bežný dospelý človek strávi 15%-20% spánku v hlbokej fáze. ",
    not_binded_hint="Nemáte prepojený MiBand s týmto účtom, prepojte ho teraz. ",
    new_record_info="WoW! Práve ste zdolali rekord v chôdzi.",
    new_record_format="Nový rekord, %d krokov, %s %d",
    today_goal_reached="Gratulujeme! Dosiahli ste váš dnešný cieľ. ",
    week_continue_reach_goal="Splnili ste váš denný cieľ po celý týždeň! To bol skvelý týždeň!",
    challenge_format="Dosiahli ste váš cieľ pre %d dní!",
    personal_best_format="Váš najväčší rekord je %d dní!",
    active_time_format_0="%dh",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Zabehli ste %s. Skvelé!",
    activie_run_format_1="Zabehli ste %s. Len tak ďalej!",
    activie_run_format_2="Zabehli ste %s, Neskutočné!",
    activie_run_consumed="Spálili ste %d cal. %s",

    get_distance_format=", celkovo %dm",
    activity_walk_format="%s Chôdza %d krokov %s",
    activity_walk_consumed_format="Spálené %d cal %s",

    activity_activity_format="%s %s v pohybe %s",
    last_night_sleeped_good_format="Minulú noc, ste spali %dh %dmin. Skvelý spánok!",
    last_night_sleeped_normal_format="Minulú noc, ste spali %dh %dmin",
    deep_sleep_format="Hlboká fáza spánku bola %dh %dmin",

    battery_low_info="Batéria je vybitá, pripojte MiBand na nabíjačku.",
    battery_very_low_info="Pripojte na nabíjačku",

    cannot_find_bracelet="Nebolo možné nájsť váš MiBand?",
    cannot_find_bracelet_info="Uistite sa, že váš MiBand je nabitý a nachádza sa v blízkosti vášho telefónu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Dosiahli ste svoj rekord!",
    new_record_born="Nový rekord!",
 }
-------------------------
-- Czech Localization String resources
-- miuios.cz (2014)
-- Kynio
-------------------------
 localization_Czech_table = {
    calories_table={
        {str="≈1 duo z vařenách vajec",	calories=96},
        {str="≈1 krajíc chleba",	calories=100},
        {str="≈1 ledový čaj",	calories=112},
        {str="≈1 omeleta",	calories=118},
        {str="≈2 masa na špejli",	calories=124},
        {str="≈1 plechovka Coca-Cola",	calories=153},
        {str="≈3 masa na špejli",	calories=186},
        {str="≈2 duo z vařených vajec",	calories=192},
        {str="≈2 krajíce chleba",	calories=200},
        {str="≈1 miska rýže",	calories=210},
        {str="≈1 chleba",	calories=221},
        {str="≈1 balíček cukroví",	calories=223},
        {str="≈2 plechovky ledového čaje",	calories=224},
        {str="≈1 malé hranolky",	calories=224},
        {str="≈1 tartelette",	calories=224},
        {str="≈2 omelety",	calories=236},
        {str="≈4 masa na špejli",	calories=248},
        {str="≈1 hamburger",	calories=260},
        {str="≈1 koblih",	calories=270},
        {str="≈1 sekaná",	calories=272},
        {str="≈3 duo z vařených vajec",	calories=288},
        {str="≈1 kornout",	calories=290},
        {str="≈3 krajíce chleba",	calories=300},
        {str="≈2 plechovky Coca-Cola",	calories=306},
        {str="≈1 střední hranolky",	calories=328},
        {str="≈3 omelety",	calories=354},
        {str="≈1 tartelette s vajíčkem",	calories=375},
        {str="≈4 krajíce chleba",	calories=400},
        {str="≈1 velké hranolky",	calories=402},
        {str="≈2 bols de riz",	calories=420},
        {str="≈2 bagety",	calories=442},
        {str="≈2 balíčky Dragibus",	calories=446},
        {str="≈2 tartelette",	calories=448},
        {str="≈1 instantní nudle",	calories=470},
        {str="≈5 krajíců chleba",	calories=500},
        {str="≈1 smažené rizoto",	calories=516},
        {str="≈2 hamburgery",	calories=520},
        {str="≈2 buchty",	calories=540},
        {str="≈2 petits pains de viande",	calories=544},
        {str="≈2 kornoutky",	calories=580},
        {str="≈1 bol de nouilles instantanées",	calories=581},
        {str="≈1 bol de nouilles au boeuf",	calories=593},
        {str="≈10 mas na šmejli",	calories=620},
        {str="≈3 bols de riz",	calories=630},
        {str="≈3 pains",	calories=663},
        {str="≈2 tartelettes aux œufs",	calories=750},
        {str="≈3 koblihy",	calories=810},
        {str="≈3 petits pains de viande",	calories=816},
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='měsíc',
    day='den',
    step="krok",
    km='km',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d h',

    welcome_use="Vítejte, já jsem váš MiBand.",
    last_week_walked_format='Minulý týden jste ušli %d kroků',
    last_week_walked_info_format='Ušli jste %d km a spálili %d cal',
    last_month_walked_format='Minulý měsíc jste ušli %d kroků',
    last_month_walked_info_format='Ušli jste %d km a spálili %d cal',

    get_over_format=", kolem %dg tuku",
    click_to_get_help="Mrkněte co dokáže MiBand",
    take_a_walk="Projděte se s MiBand",
    take_a_walk_info="MiBand bude zaznamenávat vaší aktivitu a pomůže vám být zdravější.",
    unlock_hint="Odemkněte váš telefon s MiBand,",
    unlock_hint_info="Objevte nový způsob ochrany vašeho soukromí.",
    no_data_hint_0="Hýbejte se a sportujte pro vaše zdraví.",
    no_data_hint_1="Chcete být stále šťastní? Zaběhejte si.",
    no_data_hint_2="Kardio cvičení vás osvěží a rozhýbe každý den! ",
    no_data_hint_3="Běžný dospělý člověk stráví 15%-20% spánku v hluboké fázi. ",
    not_binded_hint="Nemáte propojený MiBand s tímto účtem, propojte jej nyní. ",
    new_record_info="WoW! Právě byl zdolán rekord v chůzi.",
    new_record_format="Nový rekord, %d kroků, %s %d",
    today_goal_reached="Gratulujeme! Byl dosažen váš dnešní cíl. ",
    week_continue_reach_goal="Za poslední týden byl každý den splněn váš cíl! Byl to skvělý týden!",
    challenge_format="Byl dosažen váš cíl pro %d dní!",
    personal_best_format="Váš nejvyšší rekord je %d dní!",
    active_time_format_0="%dh",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Uběhli jste %s. Skvělé!",
    activie_run_format_1="Uběhli jste %s. Jen tak dál!",
    activie_run_format_2="Uběhli jste %s, Neskutečné!",
    activie_run_consumed="Uběhli jste %d cal. %s",

    get_distance_format=", celkem %dm",
    activity_walk_format="%s Chůze %d kroků %s",
    activity_walk_consumed_format="Spálené %d cal %s",

    activity_activity_format="%s %s v pohybu %s",
    last_night_sleeped_good_format="Minulou noc trval spánek %dh %dmin. Skvělý spánek!",
    last_night_sleeped_normal_format="Minulou noc trval spánek %dh %dmin",
    deep_sleep_format="Hluboká fáze spánku trvala %dh %dmin",

    battery_low_info="Baterie je vybitá, připojte MiBand na nabíječku.",
    battery_very_low_info="Připojte na nabíječku",

    cannot_find_bracelet="Nebylo možné najít váš MiBand?",
    cannot_find_bracelet_info="Ujistěte se, že váš MiBand je nabitý a nachází se v blízkosti vašeho telefonu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Byl dosažen váš rekord!",
    new_record_born="Nový rekord!",
 }

-------------------------
-- Croatian Localization String resources
-- adria.mobiledevs.net (2014)
-- MASVA
-------------------------
localization_Croatian_table = {
    calories_table={

    },

    ok='U redu',

    hour='sati',
    minute='min',
    month='mjesec',
    day='dan',
    step="korak",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%d sati %d min',
    hour_format='%d sati',

    welcome_use="Pozdrav, Ja sam tvoj Mi Band.",
    last_week_walked_format='Prošli tjedan, prohodali ste %d koraka.',
    last_week_walked_info_format='Prohodano %d km, potrošeno %d kal.',
    last_month_walked_format='Prošli mjesec, prohodali ste %d koraka.',
    last_month_walked_info_format='Prohodano %d km, potrošeno %d kal.',

    get_over_format=", O %d grama ili masti.",
    click_to_get_help="Saznajte što sve možete s Mi Band.",
    take_a_walk="Prošetajte s Mi Band.",
    take_a_walk_info="Mi Band će pratiti vaše aktivnosti i pomoći vam da se osjećate zdravije.",
    unlock_hint="Otključajte telefon vašim Mi Band,",
    unlock_hint_info="recite "Zbogom" starim vremenima.",
    no_data_hint_0="Nastavite se kretati, neka sport postane dijelom vašeg života.",
    no_data_hint_1="Želite oststi sretni? Samo trčite.",
    no_data_hint_2="Kardio vježba će vam omogućiti da se osjećate laganije i svježe svaki dan! ",
    no_data_hint_3="Normalna odrasla troši 15% -20% ukupnog vremena sna u dubokoj fazi sna. ",
    not_binded_hint="Nijedan Mi Band nije povezan na ovaj račun, povežite jedan sada. ",
    new_record_info="WoW! Oborili ste rekord u hodanju.",
    new_record_format="Novi rekord, %d koraka, %s %d",
    today_goal_reached="Čestitke! Postigli ste danjašnji cilj. ",
    week_continue_reach_goal="Postigli ste cilj svakog dana ovog tjedna! Stvarno fantastičan tjedan!",
    challenge_format="Postigli ste svoj cilj za %d dan(a)!",
    personal_best_format="Vaš najveći rekord je %d dan(a)!",
    active_time_format_0="%d sati",
    active_time_format_1="%d sati",
    active_time_format_2="%d sati %d min",
    activie_run_format_0="Trčano %s. Dobro je!",
    activie_run_format_1="Trčano %s. Ide vam fantastično!",
    activie_run_format_2="Trčano %s, Nevjerojatno ste izdržljivi!",
    activie_run_consumed="Potrošeno %d kal. %s",

    get_distance_format=", ukupno od %d m.",
    activity_walk_format="%s Prohodano %d koraka %s",
    activity_walk_consumed_format="Potrošeno %d kal %s",

    activity_activity_format="%s Napravljeno %s %s",
    last_night_sleeped_good_format="Prošle noći ste spavali %d sati %d min. Sad ste stvarno naspavani!",
    last_night_sleeped_normal_format="Prošle noći ste spavali %d sati %d min.",
    deep_sleep_format="Faza dubokog sna je bila %d sati %d min.",

    battery_low_info="Slaba baterija, stavite Mi Band na punjenje.",
    battery_very_low_info="Priključite na punjač",

    cannot_find_bracelet="Ne možete pronaći svoj Mi Band?",
    cannot_find_bracelet_info="Uvjerite se da vaš MiBand ima energije i nalazi se u blizini vašeg telefona.",
    challenge_to_get="%s dana od postizanja novog rekorda!",
    record_reach_max="Postigli ste svoj najveći novi rekord!",
    new_record_born="Novi rekord!",
 }
 
 