-------------------------
-- English Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_English_table = {
    calories_table={

    },

    ok='OK',

    hour='hrs',
    minute='min',
    month='month',
    day='day',
    step="step",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%d hrs %d min',
    hour_format='%d hrs',

    welcome_use="Hello, I am your Mi Band.",
    last_week_walked_format='Last week, you walked %d steps.',
    last_week_walked_info_format='Walked %d km, burned %d cal.',
    last_month_walked_format='Last month, you walked %d steps.',
    last_month_walked_info_format='Walked %d km, burned %d cal.',

    get_over_format=", about %d gram of fat.",
    click_to_get_help="Find out more to do with Mi Band.",
    take_a_walk="Take a walk with Mi Band.",
    take_a_walk_info="Mi Band will track your activities and help you to be healthier.",
    unlock_hint="Unlock phone with your Mi Band",
    unlock_hint_info="say Goodbye to the old times.",
    no_data_hint_0="Keep moving, make sports a part of your life.",
    no_data_hint_1="Want to stay happy? Just run.",
    no_data_hint_2="Cardio workout will make you light and fresh every day! ",
    no_data_hint_3="A normal adult spends 15%-20% of total sleep time in deep sleep stage. ",
    not_binded_hint="You haven’t linked any Mi Band to this account, please link one now. ",
    new_record_info="WoW! You just broke a record in walking.",
    new_record_format="New record, %d steps, %s %d",
    today_goal_reached="Congrats! You have achieved your goal today. ",
    week_continue_reach_goal="You have achieved your goal every day for an entire week! What an awesome week!",
    challenge_format="You have achieved your goal for %d days!",
    personal_best_format="Your highest record is %d days!",
    active_time_format_0="%d hr",
    active_time_format_1="%d hr",
    active_time_format_2="%d hr %d min",
    activie_run_format_0="Ran %s. Good job!",
    activie_run_format_1="Ran %s. You are doing fantastic!",
    activie_run_format_2="Ran %s, Incredible endurance!",
    activie_run_consumed="Burned %d cal. %s",

    get_distance_format=", a total of %d m.",
    activity_walk_format="%s Walked %d steps %s",
    activity_walk_consumed_format="Burned %d cal %s",

    activity_activity_format="%s %s work out%s",
    last_night_sleeped_good_format="Last night, you slept for %d hr %d min. What a great sleep!",
    last_night_sleeped_normal_format="Last night, you slept for %d hr %d min.",
    deep_sleep_format="Deep sleep stage was %d hr %d min.",

    battery_low_info="Low in battery, please charge your Mi Band.",
    battery_very_low_info="Connect to power",

    cannot_find_bracelet="Unable to find your Mi Band?",
    cannot_find_bracelet_info="Please make sure your Mi Band has power and stays nearby your phone.",

    challenge_to_get="%s days from making a new record!",
    record_reach_max="You have hit your highest record!",
    new_record_born="New record!",
 }
 
 localization_Slovak_table = {
    calories_table={
        {str="≈1 duo z varených vajec",	calories=96},
        {str="≈1 krajec chleba",	calories=100},
        {str="≈1 ľadový čaj",	calories=112},
        {str="≈1 omeleta",	calories=118},
        {str="≈2 mäsá na špajdli",	calories=124},
        {str="≈1 plechovka Coca-Cola",	calories=153},
        {str="≈3 mäsá na špajdli",	calories=186},
        {str="≈2 duo z varených vajec",	calories=192},
        {str="≈2 krajce chleba",	calories=200},
        {str="≈1 miska ryže",	calories=210},
        {str="≈1 chlieb",	calories=221},
        {str="≈1 balíček cukríkov",	calories=223},
        {str="≈2 plechovky ľadového čaju",	calories=224},
        {str="≈1 malé hranolky",	calories=224},
        {str="≈1 tartelette",	calories=224},
        {str="≈2 omeletys",	calories=236},
        {str="≈4 mäsá na špajdli",	calories=248},
        {str="≈1 hamburger",	calories=260},
        {str="≈1 beignet",	calories=270},
        {str="≈1 petit pain de viande",	calories=272},
        {str="≈3 duo z varených vajec",	calories=288},
        {str="≈1 cône",	calories=290},
        {str="≈3 krajce chleba",	calories=300},
        {str="≈2 canettes de Coca-Cola",	calories=306},
        {str="≈1 moyenne frite",	calories=328},
        {str="≈3 omeletys",	calories=354},
        {str="≈1 tartelette aux œufs",	calories=375},
        {str="≈4 krajce chleba",	calories=400},
        {str="≈1 grande frite",	calories=402},
        {str="≈2 bols de riz",	calories=420},
        {str="≈2 pains",	calories=442},
        {str="≈2 paquet de dragibus",	calories=446},
        {str="≈2 tartelettes",	calories=448},
        {str="≈1 paquet de nouilles instantanées",	calories=470},
        {str="≈5 krajce chleba",	calories=500},
        {str="≈1 assiette de riz frit",	calories=516},
        {str="≈2 hamburgers",	calories=520},
        {str="≈2 beignets",	calories=540},
        {str="≈2 petits pains de viande",	calories=544},
        {str="≈2 cônes",	calories=580},
        {str="≈1 bol de nouilles instantanées",	calories=581},
        {str="≈1 bol de nouilles au boeuf",	calories=593},
        {str="≈10 mäsá na špajdli",	calories=620},
        {str="≈3 bols de riz",	calories=630},
        {str="≈3 pains",	calories=663},
        {str="≈2 tartelettes aux œufs",	calories=750},
        {str="≈3 beignets",	calories=810},
        {str="≈3 petits pains de viande",	calories=816},
    },

    ok='OK',

    hour='hod',
    minute='min',
    month='mesiac',
    day='deň',
    step="krok",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d h',

    welcome_use="Vitajte, ja som váš MiBand",
    last_week_walked_format='Minulý týždeň ste prešli %d krokov',
    last_week_walked_info_format='Prešli ste %d km a spálili %d cal',
    last_month_walked_format='Minulý mesiac ste prešli %d krokov',
    last_month_walked_info_format='Prešli ste %d km a spálili %d cal',

    get_over_format=", okolo %d gramov tuku",
    click_to_get_help="Pozrite sa čo dokáže MiBand",
    take_a_walk="Prejdite sa s MiBand",
    take_a_walk_info="MiBand bude zaznamenávať vašu aktivitu a pomôže vám byť zdravý.",
    unlock_hint="Odomknite váš telefón s MiBand,",
    unlock_hint_info="objavte nový spôsob ochrany vášho súkromia.",
    no_data_hint_0="Hýbte sa a športujte pre vaše zdravie.",
    no_data_hint_1="Chcete byť stále šťastný? Zabehajte si.",
    no_data_hint_2="Kardio cvičenie vás osvieži a rozhýbe každý deň! ",
    no_data_hint_3="Bežný dospelý človek strávi 15%-20% spánku v hlbokej fáze. ",
    not_binded_hint="Nemáte prepojený MiBand s týmto účtom, prepojte ho teraz. ",
    new_record_info="WoW! Práve ste zdolali rekord v chôdzi.",
    new_record_format="Nový rekord, %d krokov, %s %d",
    today_goal_reached="Gratulujeme! Dosiahli ste váš dnešný cieľ. ",
    week_continue_reach_goal="Splnili ste váš denný cieľ po celý týždeň! To bol skvelý týždeň!",
    challenge_format="Dosiahli ste váš cieľ pre %d dní!",
    personal_best_format="Váš najväčší rekord je %d dní!",
    active_time_format_0="%dh",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Zabehli ste %s. Skvelé!",
    activie_run_format_1="Zabehli ste %s. Len tak ďalej!",
    activie_run_format_2="Zabehli ste %s, Neskutočné!",
    activie_run_consumed="Spálili ste %d cal. %s",

    get_distance_format=", celkovo %dm",
    activity_walk_format="%s Chôdza %d krokov %s",
    activity_walk_consumed_format="Spálené %d cal %s",

    activity_activity_format="%s %s v pohybe %s",
    last_night_sleeped_good_format="Minulú noc, ste spali %dh %dmin. Skvelý spánok!",
    last_night_sleeped_normal_format="Minulú noc, ste spali %dh %dmin",
    deep_sleep_format="Hlboká fáza spánku bola %dh %dmin",

    battery_low_info="Batéria je vybitá, pripojte MiBand na nabíjačku.",
    battery_very_low_info="Pripojte na nabíjačku",

    cannot_find_bracelet="Nebolo možné nájsť váš MiBand?",
    cannot_find_bracelet_info="Uistite sa, že váš MiBand je nabitý a nachádza sa v blízkosti vášho telefónu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Dosiahli ste svoj rekord!",
    new_record_born="Nový rekord!",
 }

 localization_Czech_table = {
    calories_table={

    },

    ok='OK',

    hour='hod',
    minute='min',
    month='měsíc',
    day='den',
    step="krok",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%dh %dm',
    hour_format='%d h',

    welcome_use="Vítejte, já jsem váš MiBand.",
    last_week_walked_format='Minulý týden jste ušli %d kroků',
    last_week_walked_info_format='Ušli jste %d km a spálili %d cal',
    last_month_walked_format='Minulý měsíc jste ušli %d kroků',
    last_month_walked_info_format='Ušli jste %d km a spálili %d cal',

    get_over_format=", kolem %dg tuku",
    click_to_get_help="Mrkněte co dokáže MiBand",
    take_a_walk="Projděte se s MiBand",
    take_a_walk_info="MiBand bude zaznamenávat vaší aktivitu a pomůže vám být zdravější.",
    unlock_hint="Odemkněte váš telefon s MiBand,",
    unlock_hint_info="Objevte nový způsob ochrany vašeho soukromí.",
    no_data_hint_0="Hýbejte se a sportujte pro vaše zdraví.",
    no_data_hint_1="Chcete být stále šťastní? Zaběhejte si.",
    no_data_hint_2="Kardio cvičení vás osvěží a rozhýbe každý den! ",
    no_data_hint_3="Běžný dospělý člověk stráví 15%-20% spánku v hluboké fázi. ",
    not_binded_hint="Nemáte propojený MiBand s tímto účtem, propojte jej nyní. ",
    new_record_info="WoW! Právě byl zdolán rekord v chůzi.",
    new_record_format="Nový rekord, %d kroků, %s %d",
    today_goal_reached="Gratulujeme! Byl dosažen váš dnešní cíl. ",
    week_continue_reach_goal="Za poslední týden byl každý den splněn váš cíl! Byl to skvělý týden!",
    challenge_format="Byl dosažen váš cíl pro %d dní!",
    personal_best_format="Váš nejvyšší rekord je %d dní!",
    active_time_format_0="%dh",
    active_time_format_1="%dh",
    active_time_format_2="%dh %dmin",
    activie_run_format_0="Uběhli jste %s. Skvělé!",
    activie_run_format_1="Uběhli jste %s. Jen tak dál!",
    activie_run_format_2="Uběhli jste %s, Neskutečné!",
    activie_run_consumed="Uběhli jste %d cal. %s",

    get_distance_format=", celkem %dm",
    activity_walk_format="%s Chůze %d kroků %s",
    activity_walk_consumed_format="Spálené %d cal %s",

    activity_activity_format="%s %s v pohybu %s",
    last_night_sleeped_good_format="Minulou noc trval spánek %dh %dmin. Skvělý spánek!",
    last_night_sleeped_normal_format="Minulou noc trval spánek %dh %dmin",
    deep_sleep_format="Hluboká fáze spánku trvala %dh %dmin",

    battery_low_info="Baterie je vybitá, připojte MiBand na nabíječku.",
    battery_very_low_info="Připojte na nabíječku",

    cannot_find_bracelet="Nebylo možné najít váš MiBand?",
    cannot_find_bracelet_info="Ujistěte se, že váš MiBand je nabitý a nachází se v blízkosti vašeho telefonu.",
    challenge_to_get="%s dní od nového rekordu!",
    record_reach_max="Byl dosažen váš rekord!",
    new_record_born="Nový rekord!",
 }
